# Generated by Django 5.1 on 2024-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
