# Generated by Django 5.1 on 2024-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0002_shoppinglist_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
