# Generated by Django 5.1 on 2024-12-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0003_shoppinglist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='status',
            field=models.CharField(blank=True, default='processing order', max_length=255, null=True),
        ),
    ]
