# Generated by Django 5.1 on 2024-12-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0006_userinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
