# Generated by Django 5.1 on 2026-03-18 19:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import ussd_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0007_userinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_preference', models.CharField(blank=True, choices=[('MTN MoMo', 'MTN MoMo'), ('Vodafone Cash', 'Vodafone Cash')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reservation_code', models.CharField(default=ussd_app.models.generate_reservation_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=10)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ussd_app.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MTN MoMo', 'MTN MoMo'), ('Vodafone Cash', 'Vodafone Cash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ussd_app.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=django.utils.timezone.localdate)),
                ('window', models.CharField(choices=[('MORN', 'Morning'), ('EVE', 'Evening')], max_length=4)),
                ('departure_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=36, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='ussd_app.route')),
            ],
            options={
                'unique_together': {('route', 'service_date', 'window', 'departure_time')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ussd_app.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('trip', 'seat_number')},
        ),
    ]
